version: "3"
services:
  reverseproxy:
    build:
      context: ./instapet-proxy
    image: nguyendk82/reverseproxy 
  instapet_user:
    build:
      context: ./instapet-user
    image: nguyendk82/instapet-user
  instapet_feed:
    build:
      context: ./instapet-feed  
    image: nguyendk82/instapet-feed
  instapet-web:
    build:
      context: ./instapet-web
    image: nguyendk82/instapet-web:local
