apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: instapet
  region: us-west-2

nodeGroups:
  - name: instapet-nodegroup
    instanceType: t2.micro
    minSize: 2
    maxSize: 10
    iam:
        withAddonPolicies:
          albIngress: true
          autoScaler: true
          cloudWatch: true



cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator"]