apiVersion: v1
kind: Service
metadata:
  labels:
    service: instapet-web
  name: instapet-web
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  selector:
    service: instapet-web
#  type: LoadBalancer    
