apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: instapet-web
  name: instapet-web-a
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: instapet-web
        api: external        
    spec:
      containers:
      - image: nguyendk82/instapet-web:local
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always

